#for coding
server:
  port: 8081

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
    check-template-location: true
  application:
    name: app-item
eureka:
  client:
    service-url:
      defaultZone: http://testuser:666666@127.0.0.1:8100/eureka,http://testuser:666666@127.0.0.1:9100/eureka
    fetch-registry: true
    register-with-eureka: true

