
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
    check-template-location: true

#  cloud:
#    config:
#      uri: 127.0.0.1:7788
#      profile: dev
##      discovery:
##        enabled: true
##        service-id: microservice-config-server
#      label: master
